<div style="	width: 496px;
	border-radius: 4px;
	box-sizing: border-box;
	padding: 0 45px;
	margin: 40px auto;
	overflow: hidden;
	border: 1px solid #b0afb5;
	font-family: 'Open Sans', sans-serif;
	color: #4f5365;">
    <div>
        <div style="position: relative;
      	top: -1px;
      	padding: 9px 0 10px;
      	font-size: 11px;
      	text-transform: uppercase;
      	text-align: center;
      	color: #ffffff;
      	background: #000000;">Ficha digital. No es necesario imprimir.</div>
        <div style="margin-top: 26px;
      	position: relative;">
            <div ><?php echo makeHTMLImg($MyRequest->link(getImg("oxxopay_brand.png"),false,true),"","","OXXOPay","style='max-width: 150px;margin-top: 2px;'"); ?></div>
            <div style="width: 55%;
          	float: right;">
                <h3>Monto a pagar ID: <?php echo $referencia; ?></h3>
                <h2 style="font-size: 16px; position: relative; top: -2px"><?php echo getFormatoPrecio($productos_comprados['gran_total']); ?></h2>
                <p style="font-size: 10px;
              	line-height: 14px;">OXXO cobrará una comisión adicional al momento de realizar el pago.</p>
            </div>
        </div>
        <div style="margin-top: 14px;">
            <h3>Referencia</h3>
            <h1 style='font-size: 27px;
          	color: #000000;
          	text-align: center;
          	margin-top: -1px;
          	padding: 6px 0 7px;
          	border: 1px solid #b0afb5;
          	border-radius: 4px;
          	background: #f8f9fa;'><?php echo $code_referencia; ?></h1>
        </div>
    </div>
    <div style="margin: 32px -45px 0;
  	padding: 32px 45px 45px;
  	border-top: 1px solid #b0afb5;
  	background: #f8f9fa;">
        <h3>SE COMPRO</h3>
        <?php
        foreach($productos_comprados['productos'] as $producto)
        {
            ?>
            <?=$producto["nombre"]?> <?=getFormatoPrecio($producto["precio"])?> x <?=$producto["qty"]?><br />
            <?php
        }
        ?>
        <h3>Instrucciones</h3>
        <ol>
                <li>Acude a la tienda OXXO más cercana. <a href="https://www.google.com.mx/maps/search/oxxo/" target="_blank">Encuéntrala aquí</a>.</li>
                <li>Indica en caja que quieres ralizar un pago de <strong>OXXOPay</strong>.</li>
                <li>Dicta al cajero el número de referencia en esta ficha para que tecleé directamete en la pantalla de venta.</li>
                <li>Realiza el pago correspondiente con dinero en efectivo.</li>
                <li>Al confirmar tu pago, el cajero te entregará un comprobante impreso. <strong>En el podrás verificar que se haya realizado correctamente.</strong> Conserva este comprobante de pago.</li>
        </ol>
        <div style="margin-top: 22px;
      	padding: 22px 20 24px;
      	color: #108f30;
      	text-align: center;
      	border: 1px solid #108f30;
      	border-radius: 4px;
      	background: #ffffff;">Al completar estos pasos recibirás un correo de <strong>Nombre del negocio</strong> confirmando tu pago.</div>
    </div>
</div>
