<?php echo $MetodoEnvioCheckoutForm->openTag(); ?>
<?php echo $MetodoEnvioCheckoutForm->getRow("id_metodo_envio"); ?>
<?php echo $MetodoEnvioCheckoutForm->getRow("continuar"); ?>
<label for="id_metodo_envio" class="error" style="display:none;"></label>
<?php echo $MetodoEnvioCheckoutForm->endTag(); ?>

<?php if(isset($pickupForm)):?>
<div id="form_pick-up" style="display:none ;">
    <?php echo $pickupForm->openTag(); ?>
    <?php echo $pickupForm->getAllRow(); ?>
    <?php echo $pickupForm->endTag(); ?>
</div>
<?php endif; ?>

