<div class="w-xxxx-12">
    <div class="w-xxxx-10">
        <?=$direccion_envio['nombre']?>: calle <?=$direccion_envio['calle']?> #<?=$direccion_envio['numero']?>, Colonia <?=$direccion_envio['colonia']?>, municipio <?=$direccion_envio['municipio']?>,<?=$direccion_envio['pais']?> C.P. <?=$direccion_envio['cp']?>
    </div>
    <div class="w-xxxx-2">
        <a href="javascript:void(0)" onclick="changeShippingAddress();"><i class="icon icon-editar"></i> Cambiar</a>
    </div>
    </div>
