<div class="w-xxxx-12">
    <h4>Recoger en tienda</h4>
    <div class="w-xxxx-10">
        <b><?=$pickup['nombre']?></b>
        calle <?=$pickup['calle']?> #<?=$pickup['numero']?>, Colonia <?=$pickup['colonia']?>, municipio <?=$pickup['municipio']?>,<?=$pickup['pais']?> C.P. <?=$pickup['cp']?>
    </div>
    <div class="w-xxxx-2">
        <a href="javascript:void(0)" onclick="changeMetodoEnvio();"><i class="icon icon-editar"></i> Cambiar</a>
    </div>
    </div>
