<?php if(!empty($detalle_pedido)): ?>
<div class="order_content">
<h4>Resumen de la orden<h4>

<div  class="content_carrito">


<?php foreach($detalle_pedido['productos'] as $producto): ?>

    <div class="_list_mycart_product contenedor_producto_<?php echo $_carrito_compras["id"]; ?>">
                    <div class="_mycart_resume">
<?php
$imagen = "";
    $_img = getCoreConfig('ecommerce/product/placeholder');
    if($_img != "" && file_exists(PROJECT_DIR.$_img))
    {
      $imagen = imageResize($_img,50,50, true);
    }

    if(!empty($producto["imagen"]))
    {
        $_imagen = json_decode($producto["imagen"],true);
        if(is_array($_imagen))
        {
            if(!empty($_imagen)){

                foreach($_imagen as $foto)
                {
                    if($foto['principal'] == 1)
                    {
                        if(!empty($foto["img"]) && file_exists($MyConfigure->getServerUploadDir()."/".DIRECTORIO_IMAGENES_PRODUCTOS_ECOMMERCE.'/'.$producto["id"].'/'.$foto['img']))
                        {
                            $imagen = imageResize($MyConfigure->getUploadDir()."/".DIRECTORIO_IMAGENES_PRODUCTOS_ECOMMERCE."/".$producto["id"].'/'.$foto['img'],50,50, true);
                        }
                    }
                }
            }
        }
        else{
            $imagen = imageResize($MyConfigure->getUploadDir()."/".DIRECTORIO_IMAGENES_PRODUCTOS_ECOMMERCE."/".$producto["id"].'/'.$producto['imagen'],50,50, true);
        }
    }


    ?>
  <div class="_col_mycart_resume _img_product">
      <?=makeHTMLImg($imagen,50,50,$producto['nombre'])?>
    </div>
    <div class="_col_mycart_resume _name">
                            <div class="_row_mycart_resume">
                                <h3><?php echo $producto['nombre']; ?></h3>
                            </div>

                            <?php if(!empty($producto['caracteristicas'])): ?>
                                    <ul class="caracteristicas">
                                    <?php foreach($producto['caracteristicas'] as $caracteristicas): ?>
                                   
                                        <li><strong><?=$caracteristicas['name']?>:</strong><span><?=$caracteristicas['value']?></span></li>
                                    <?php endforeach; ?>
                                    </ul>
                                <?php endif; ?>

    </div>
    <div class='_col_mycart_resume _cont_control_qty'><?php echo $producto['qty']; ?></div>
    <div class="_col_mycart_resume subtotal_producto"><strong>Precio:</strong> <?php echo getFormatoPrecio($producto['precio']); ?></div>


</div>
</div>
<?php endforeach; ?>
</div>
</div>
<?php endif; ?>
