<script >
function BrowseFiles(field_name,url,type,win) {

        var url_p = '/mfm.php?mode=standalone&field='+field_name+"&url=" + url+"&pwd=email_template/<?php echo $path_img_blog; ?>";
        var winpops=window.open(url_p,"","status = 1, height = 450, width = 640, left = 200, top = 180, resizable = 0")
}
$(window).load(function(){
    tinymce.init({

            selector: "textarea",

            plugins: [
                    "advlist autolink  link image lists charmap print preview hr anchor pagebreak spellchecker",
                    "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
                    "table contextmenu directionality emoticons template textcolor paste textcolor"
            ],

            toolbar1: "newdocument fullpage | bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | styleselect formatselect fontselect fontsizeselect",
            toolbar2: "cut copy paste | searchreplace | bullist numlist | outdent indent blockquote | undo redo | link unlink anchor image media code | inserttime preview | forecolor backcolor",
            toolbar3: "table | hr removeformat | subscript superscript | charmap emoticons | print fullscreen | ltr rtl | spellchecker | visualchars visualblocks nonbreaking template pagebreak restoredraft",

            menubar: false,
            toolbar_items_size: 'small',

            style_formats: [
                    {title: 'Bold text', inline: 'b'},
                    {title: 'Red text', inline: 'span', styles: {color: '#ff0000'}},
                    {title: 'Red header', block: 'h1', styles: {color: '#ff0000'}},
                    {title: 'Example 1', inline: 'span', classes: 'example1'},
                    {title: 'Example 2', inline: 'span', classes: 'example2'},
                    {title: 'Table styles'},
                    {title: 'Table row 1', selector: 'tr', classes: 'tablerow1'}
            ],

            templates: [
                    {title: 'Test template 1', content: 'Test 1'},
                    {title: 'Test template 2', content: 'Test 2'}
            ],
            relative_urls: false,
            remove_script_host: false,
            file_browser_callback: BrowseFiles
    });
});


</script>
<div class="content">
    <div class="w-xxxx-12"><?php echo breadcrumbs(); ?></div>
    <div class="w-xxxx-12">
         <div class="w-xxxx-8 m-l-xxxx-2">
             <h1><?php echo $title_form; ?></h1>
             <p>LISTA_EMAIL_TEMPLATE</p>
            <?php echo $adminForm->openTag(); ?>
            <?php echo $adminForm->getAllRow(); ?>
            <?php echo $adminForm->endTag(); ?>
       </div>
    </div>
</div>
