<div class="cont_news">
    <form class="form_newsletter" action="">
    <p>Regístrate y recibe antes que nadie noticias y promociones</p>
    <div id="msg_mailing" style="display:none;"><span class="error"></span></div>
    <div class="cont_input_button_newsletter">
        <input type="text" placeholder="Tu email..." name="mailing"><button class="_btn _secondary" onclick="registrarEmail(); return false;">Enviar</button>
    </div>
    </form>
</div>
