<div class="w-xxxx-12">
      <div class="content">
   <div class="w-xxxx-2 w-xxx-3 w-xx-4 cont-submenu">
       <?php echo render("blog/lateral.phtml"); ?>
   </div>
    <div class="w-xxxx-10 w-xxx-9 w-xx-8 cont-cont-gral">
        <h1><?php echo _blog("Blog"); ?></h1>
        <div class="w-xxxx-12">
            <div class="content">
                <?php echo makeHTMLImg(getImg('article.jpg'),"","","","class='image_100'"); ?>
                <div class="_blog_txt_principal_article">
                    <h2>Tutilo del artículo</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga, numquam?</p>
                    <ul class="_ul_tag">
                        <li>Tag 1</li>
                        <li>Tag 1</li>
                    </ul>
                    <a class="_ver_mas link_detalle_revista" href="/">Ver más</a>
                </div>
            </div>
        </div>
        <?php if(!empty($lista_articulos_blog)): ?>
        <?php foreach ($lista_articulos_blog as $articulo): ?>
            <div class="w-xxxx-6 _cont_card_blog">
                    <h3><a href="<?php echo $articulo["link"]; ?>"><?php echo $articulo["titulo"]; ?></a></h3>
                    <!-- <li>Categoria: <?php // echo $articulo["categoria"]; ?></li> -->
                    <!--  <li><span><?php // echo $articulo["fecha"]; ?></span></li> -->
                    <!-- <li>Autor: <?php // echo $articulo["autor"]; ?></li> -->
                        <?php if(isset($articulo["contenido"]["img"])): ?>
                                <a href="<?php echo $articulo["link"]; ?>"><?php echo makeHTMLImg($articulo["contenido"]["img"],"","", $articulo["titulo"],'class="image_100"',1); ?></a>
                        <?php endif;  ?>

                        <?php if(isset($articulo["contenido"]["p"])): ?>

                                <p><?php echo $articulo["contenido"]["p"]; ?></p>
                        <?php endif; ?>


                        <a class="float_right" href="<?php echo $articulo["link"]; ?>">ver más<i class="icon icon-flecha-r-1"></i></a>
            </div>
        <?php endforeach; ?>
        <div class="w-xxxx-12 cont-paginar"><?php echo render("widget.paginar.phtml"); ?></div>
        <?php else: ?>
        <p class="error">No existen articulos registrados</p>
        <?php endif; ?>
    </div>
    </div>
</div>
