<script >
function BrowseFiles(field_name,url,type,win) {


        var url_p = '/mfm.php?mode=standalone&field='+field_name+"&url=" + url+"&pwd=cms/<?php echo $path_img_blog; ?>";
        var winpops=window.open(url_p,"","status = 1, height = 450, width = 640, left = 200, top = 180, resizable = 0")
}

tinymce.init({
selector: 'textarea',
height: 500,
menubar: false,
codesample_dialog_width: '600',
codesample_dialog_height: '400',
plugins: [
'advlist autolink lists link image charmap print preview anchor textcolor',
'searchreplace visualblocks code fullscreen',
'insertdatetime media table contextmenu paste code help  codesample'
],
toolbar: 'insert | undo redo |  formatselect | bold italic backcolor  | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat |  table code | help',
content_css: [],
relative_urls: true,
remove_script_host: false,
file_browser_callback: BrowseFiles
});

// -->
</script>

<div class="content">
    <div class="w-xxxx-12"><?php echo breadcrumbs(); ?></div>
    <h1 class="titulo_seccion_admin"><?php echo $title_form; ?></h1>
    <div class="w-xxxx-12">
    <?php echo $cmsForm->openTag(); ?>
      <?php echo $cmsForm->get('id'); ?>
      <?php echo $cmsForm->get('callback'); ?>
      <?php echo $cmsForm->getRow('titulo'); ?>
      <?php echo $cmsForm->getRow('mostrar_titulo'); ?>
      <?php echo $cmsForm->getRow('template'); ?>
      <?php echo $cmsForm->getRow('meta_titulo'); ?>
      <?php echo $cmsForm->getRow('meta_descripcion'); ?>
      <?php echo $cmsForm->getRow('friendly'); ?>
      <div class="form-group form_guardar">
        <?php echo $cmsForm->get('guardar_editar'); ?>
        <?php echo $cmsForm->get('guardar'); ?>
      </div>
    <?php echo $cmsForm->endTag(); ?>
   </div>
</div>


<script>
$('input[name=guardar_editar]').click(function(e){

  $('input[name=callback]').val('<?= $MyRequest->getURI()?>');
});
</script>