<?php
$MyAccessList = new \Franky\Core\AccessList();

define("NIVEL_USERPUBLICO",		0);
define("NIVEL_USERADMIN",		1);
define("NIVEL_USERSEO",                 2);
define("NIVEL_USERSUSCRIPTOR",		3);
define("NIVEL_USERDEVELOPER",		777);


$_Niveles_usuarios = array(
    NIVEL_USERADMIN => "Aministrador",
    NIVEL_USERSUSCRIPTOR => "Suscriptor",
    NIVEL_USERSEO => "SEO",
    NIVEL_USERDEVELOPER => "Developer"
);




// ADMINISTRACION DE USUARIOS
define("ADMINISTRAR_OTROS_USUARIOS",        "administrar_otros_usuarios");

$MyAccessList->addRoll(NIVEL_USERADMIN,ADMINISTRAR_OTROS_USUARIOS);
$MyAccessList->addRoll(NIVEL_USERDEVELOPER,ADMINISTRAR_OTROS_USUARIOS);

define("ADMINISTRAR_OTRA_CONTRASENA",       "administrar_otra_contrasena");

$MyAccessList->addRoll(NIVEL_USERADMIN,ADMINISTRAR_OTRA_CONTRASENA);
$MyAccessList->addRoll(NIVEL_USERDEVELOPER,ADMINISTRAR_OTRA_CONTRASENA);

define("ADMINISTRAR_MI_USUARIO",            "administrar_mi_usuario");


$MyAccessList->addRoll(NIVEL_USERSEO,ADMINISTRAR_MI_USUARIO);
$MyAccessList->addRoll(NIVEL_USERSUSCRIPTOR,ADMINISTRAR_MI_USUARIO);

define("ADMINISTRAR_MI_CONTRASENA",         "administrar_mi_contrasena");

$MyAccessList->addRoll(NIVEL_USERADMIN,ADMINISTRAR_MI_CONTRASENA);
$MyAccessList->addRoll(NIVEL_USERDEVELOPER,ADMINISTRAR_MI_CONTRASENA);
$MyAccessList->addRoll(NIVEL_USERSEO,ADMINISTRAR_MI_CONTRASENA);
$MyAccessList->addRoll(NIVEL_USERSUSCRIPTOR,ADMINISTRAR_MI_CONTRASENA);

define("ELIMINAR_MI_PERFIL",                "eliminar_mi_perfil");

$MyAccessList->addRoll(NIVEL_USERADMIN,ELIMINAR_MI_PERFIL);
$MyAccessList->addRoll(NIVEL_USERDEVELOPER,ELIMINAR_MI_PERFIL);
$MyAccessList->addRoll(NIVEL_USERSEO,ELIMINAR_MI_PERFIL);
$MyAccessList->addRoll(NIVEL_USERSUSCRIPTOR,ELIMINAR_MI_PERFIL);

// ADMINISTRACION PARTICIPACION
define("ADMINISTRAR_MAILING",               "administrar_mailing");
$MyAccessList->addRoll(NIVEL_USERADMIN,ADMINISTRAR_MAILING);
$MyAccessList->addRoll(NIVEL_USERDEVELOPER,ADMINISTRAR_MAILING);
$MyAccessList->addRoll(NIVEL_USERSEO,ADMINISTRAR_MAILING);

define("ADMINISTRAR_CONTACTANOS",     "administrar_contactanos");

$MyAccessList->addRoll(NIVEL_USERADMIN,ADMINISTRAR_CONTACTANOS);
$MyAccessList->addRoll(NIVEL_USERDEVELOPER,ADMINISTRAR_CONTACTANOS);
$MyAccessList->addRoll(NIVEL_USERSEO,ADMINISTRAR_CONTACTANOS);

// ADMINISTRACION TEMPLATES DE EMAIL
define("ADMINISTRAR_EMAIL_TEMPLATE",         "administrar_template_de_mailings");
$MyAccessList->addRoll(NIVEL_USERADMIN,ADMINISTRAR_EMAIL_TEMPLATE);
$MyAccessList->addRoll(NIVEL_USERDEVELOPER,ADMINISTRAR_EMAIL_TEMPLATE);
$MyAccessList->addRoll(NIVEL_USERSEO,ADMINISTRAR_EMAIL_TEMPLATE);

// ADMINISTRACION TEMPLATES DE CMS
define("ADMINISTRAR_CMS_TEMPLATE",         "administrar_template_de_cms");
$MyAccessList->addRoll(NIVEL_USERADMIN,ADMINISTRAR_CMS_TEMPLATE);
$MyAccessList->addRoll(NIVEL_USERDEVELOPER,ADMINISTRAR_CMS_TEMPLATE);



// ADMINISTRACION TEMPLATES DE EMAIL
define("ADMINISTRAR_PAQUETES",      "administrar_paquetes");
$MyAccessList->addRoll(NIVEL_USERADMIN,ADMINISTRAR_PAQUETES);
$MyAccessList->addRoll(NIVEL_USERDEVELOPER,ADMINISTRAR_PAQUETES);

define("ADMINISTRAR_UPLOADERS",      "administrar_uploaders");
$MyAccessList->addRoll(NIVEL_USERADMIN,ADMINISTRAR_UPLOADERS);
$MyAccessList->addRoll(NIVEL_USERDEVELOPER,ADMINISTRAR_UPLOADERS);


define("ADMINISTRAR_URLINTERNACIONAL",      "administrar_urlinternacional");
$MyAccessList->addRoll(NIVEL_USERADMIN,ADMINISTRAR_URLINTERNACIONAL);
$MyAccessList->addRoll(NIVEL_USERDEVELOPER,ADMINISTRAR_URLINTERNACIONAL);
$MyAccessList->addRoll(NIVEL_USERSEO,ADMINISTRAR_URLINTERNACIONAL);


define("ADMINISTRAR_CORE_CONFIG" , "administrar_core_sistem");
$MyAccessList->addRoll(NIVEL_USERADMIN,ADMINISTRAR_CORE_CONFIG);
$MyAccessList->addRoll(NIVEL_USERDEVELOPER,ADMINISTRAR_CORE_CONFIG);

define("ADMINISTRAR_DEVICES",     "administrar_devices");
$MyAccessList->addRoll(NIVEL_USERADMIN,ADMINISTRAR_DEVICES);
$MyAccessList->addRoll(NIVEL_USERDEVELOPER,ADMINISTRAR_DEVICES);
$MyAccessList->addRoll(NIVEL_USERSEO,ADMINISTRAR_DEVICES);
$MyAccessList->addRoll(NIVEL_USERSUSCRIPTOR,ADMINISTRAR_DEVICES);
?>
