<?php echo render("admin/template/form.phtml"); ?>
<?php
if(getCoreConfig('ecommerce/conekta/enabled') == 1 && in_array('conekta_tarjeta',getCoreConfig('ecommerce/conekta/methods')))
{
	echo render("admin/tarjetas/validate.conekta.phtml");
}
elseif(getCoreConfig('ecommerce/openpay/enabled') == 1 && in_array('openpay_tarjeta',getCoreConfig('ecommerce/openpay/methods')))
{
	echo render("admin/tarjetas/validate.openpay.phtml");
}
?>
