<?php if(getCoreConfig('ecommerce/sr-pago/enabled') == 1 && in_array('srpago_tarjeta',getCoreConfig('ecommerce/sr-pago/methods'))): ?>

    <?php
    $adminForm = new \Ecommerce\Form\srpagoForm("card-payment-form");
    $data = $MyFlashMessage->getResponse();
    $adminForm->setData($data);
    $adminForm->setAtributoInput("pagar", "value", "Validar tarjeta");
    ?>

    <?php echo render("admin/template/form.phtml",['adminForm' => $adminForm]); ?>
    <script type="text/javascript" src="https://js.srpago.com/v1/srpago.min.js"></script>
    <script type="text/javascript" src="https://js.srpago.com/v1/srpago.encryption.min.js"></script>
    <script >
    var SrPagoonSuccessHandler = function(result){
        //console.log(result);
        $("input[name=tokenInput]").val(result.token);
        
        document.getElementById("card-payment-form").submit(); 
    };
    var SrPagoonFailHandler = function(error){
        _alert("Error " + error.code + ": " + error.message);
    };

    $(document).ready(function()
    {

        $("form[name=card-payment-form]").validate({
            ignore: [],
            rules: {

                'holder_name': {
                   required: true,
                },
                'number': {
                   required: true,
                //   minlength: 12,
                  //  maxlength: 12
                },
                'cvv': {
                    required: true,
                    minlength:3,
                    maxlength: 3
                },
                'month': {
                    required: true
                },
                'year': {
                    required: true
                }

            },
            messages: {

                'holder_name': {
                    required: "Favor de escribir el nombre de la tarjeta"
                },
                'number': {
                    required: "Favor de escribir el n&uacute;mero de la tarjeta",
                    minlength: "El n&uacute;mero de tarjeta debe tener 12 numeros",
                    maxlength: "El n&uacute;mero de tarjeta debe tener 12 numeros",
                },
                'cvv': {
                   required: "Favor de escribir el n&uacute;mero de seguridad",
                    minlength: "El n&uacute;mero de seguridad debe tener 3 numeros",
                    maxlength: "El n&uacute;meros de seguridad debe tener 3 numeros",
                },
                 'month': {
                   required: "Favor de seleccionar el mes de expiraci&oacute;n",
                },
                'year': {
                   required: "Favor de seleccionar el a&ntilde;o de expiraci&oacute;n"
                },

            },

             invalidHandler: function(event, validator) {


              },
            submitHandler: function() {

                SrPago.setLiveMode(<?=(getCoreConfig('ecommerce/sr-pago/sandbox') ? 'false': 'true')?>);
                SrPago.setPublishableKey("<?=getCoreConfig('ecommerce/sr-pago/public')?>");
                

                
                var card = {
                    number: $('input[name=number]').val(),
                    holder_name: $('input[name=holder_name]').val(),
                    cvv: $('input[name=cvv]').val(),
                    exp_month: $('select[name=month]').val(),
                    exp_year: $('select[name=year]').val()
                };        
                SrPago.token.create(card,SrPagoonSuccessHandler,SrPagoonFailHandler);

                return false

            },
            onkeyup: false,
            errorClass: "invalid-input error",
            validClass: "valid-input"

        });
    });

    </script>
<?php endif; ?>