<?php if(getCoreConfig('ecommerce/conekta/enabled') == 1 && in_array('conekta_tarjeta',getCoreConfig('ecommerce/conekta/methods'))): ?>
    <?php
    $adminForm = new \Ecommerce\Form\conektaForm("card-form");
    $data = $MyFlashMessage->getResponse();
    $adminForm->setData($data);
    $adminForm->setAtributoInput("pagar", "value", "Validar tarjeta");
    ?>
    <?php echo render("admin/template/form.phtml",['adminForm' => $adminForm]); ?>
    <script  type="text/javascript" src="https://cdn.conekta.io/js/latest/conekta.js"></script>
    <script>
    var conektaSuccessResponseHandler = function(token) {
      var $form = $("#card-form");
      $form.append($("<input name=\"token\" type=\"hidden\">").val(token.id));
      $form.get(0).submit();
    };

    var conektaErrorResponseHandler = function(response) {
       var $form = $("#card-form");
      // console.log(response);
      _alert(response.message_to_purchaser,"Error");
      $form.find("input[type=submit]").prop("disabled", false);

      return false;
    };
    $(document).ready(function()
    {

        $("form[name=card-form]").validate({
            ignore: [],
            rules: {

                'card[name]': {
                   required: true,
                },
                'card[number]': {
                   required: true,
                //   minlength: 12,
                  //  maxlength: 12
                },
                'card[cvc]': {
                    required: true,
                    minlength:3,
                    maxlength: 3
                },
                'card[exp_month]': {
                    required: true
                },
                'card[exp_year]': {
                    required: true
                }

            },
            messages: {

                'card[name]': {
                    required: "Favor de escribir el nombre de la tarjeta"
                },
                'card[number]': {
                    required: "Favor de escribir el n&uacute;mero de la tarjeta",
                    minlength: "El n&uacute;mero de tarjeta debe tener 12 numeros",
                    maxlength: "El n&uacute;mero de tarjeta debe tener 12 numeros",
                },
                'card[cvc]': {
                   required: "Favor de escribir el n&uacute;mero de seguridad",
                    minlength: "El n&uacute;mero de seguridad debe tener 3 numeros",
                    maxlength: "El n&uacute;meros de seguridad debe tener 3 numeros",
                },
                 'card[exp_month]': {
                   required: "Favor de seleccionar el mes de expiraci&oacute;n",
                },
                'card[exp_year]': {
                   required: "Favor de seleccionar el a&ntilde;o de expiraci&oacute;n"
                },

            },

             invalidHandler: function(event, validator) {


              },
            submitHandler: function() {

                Conekta.setPublicKey('<?php echo (getCoreConfig('ecommerce/conekta/sandbox') == 1 ? getCoreConfig('ecommerce/conekta/publicsandbox') :  getCoreConfig('ecommerce/conekta/public')); ?>');

                //jQuery generate the token on submit.

                var $form = $("form[name=card-form]");
                // Prevents double clic

                $form.find("input[type=submit]").prop("disabled", true);

                Conekta.token.create($form, conektaSuccessResponseHandler, conektaErrorResponseHandler);

                return false

            },
            onkeyup: false,
            errorClass: "invalid-input error",
            validClass: "valid-input"

        });
    });
    </script>
<?php endif; ?>