<?php if(!$MySession->LoggedIn()): ?>
<?php $loginFormRating = new Base\Form\loginForm("autentificacion_rating"); ?>
<?php echo $loginFormRating->addCallback($MyRequest->link($MyRequest->getURI())); ?>
<div class="deja_comment rating_login" style="display:none;">
       
        <div class="w_50">
            <p>Para comentar necesitas estar registrado</p>
             <?php echo $loginFormRating->openTag(); ?>
            <?php echo $loginFormRating->getAllRow(); ?>
            <?php echo $loginFormRating->endTag(); ?>
            <a class="olvide_contrasena_comm" href="<?php echo $MyRequest->url(FORGOT); ?>">Olvide mi contraseña</a>
           
        </div>
        
        <div class="w_50">
            <!--
            <p>Ó conetate con:<p>
            <a class="button-facebook" href="javascript:void(0)">FB CONNECT</a>
            <a class="button-twitter" href="javascript:void(0)">TW CONNECT</a>
            -->
        </div>
    </div>
<?php endif; ?>