<?php if($MyAccessList->MeDasChancePasar(CARRITO_ECOMMERCE)): ?>

<form name="addCartForm" action="">
  <div class='control_qty'>

      <div class='w-xxxx-12'>
          <h3>QTY:</h3>
          <div class='w-xxxx-2'><a class="menos_qty" data-id='<?php echo $_carrito_compras["id"]; ?>' href="#"><i class='icon icon-c-eliminar'></i></a></div>
          <div class='w-xxxx-8'><input type="text" data-id='<?php echo $_carrito_compras["id"]; ?>' value="1" name="qty"  class="required"  /></div>
          <div class='w-xxxx-2'><a class="mas_qty"  data-id='<?php echo $_carrito_compras["id"]; ?>'  href="#"><i class='icon icon-c-agregar'></i></a></div>
      </div>
      <label id="qty-error" class="error" for="qty" style="display:none;"></label>
  </div>



   <div class='w-xxxx-12'><a class="_btn_add" href="javascript:void(0)" onclick="validateAddCart();"><i class='icon icon-mi-carrito'></i> Agregar a carrito</a></div>
</form>

<script >
<!--
$(document).ready(function(){
    $("a.menos_qty").click(function(e){
        e.preventDefault();
        var qty = parseInt($("input[name=qty]").val());
        if(qty > 1)
        {
            $("input[name=qty]").val(qty-1);
        }
    });
    $("a.mas_qty").click(function(e){
        e.preventDefault();
        var qty = parseInt($("input[name=qty]").val());
        $("input[name=qty]").val(qty+1);
    });

});
function validateAddCart()
{
    if($('form[name=addCartForm]').valid())
    {
        catalog_addProductoCarrito('<?php echo $id_producto; ?>',$('input[name=qty]').val());
    }

}
// -->
</script>

<?php endif; ?>
