<div class="w-xxxx12 _wrapper_avatar">
  <div class="w-xxxx12">
  <h3>Elige el avatar de tu perfil</h3>
  <div class="align_left margin_top">
    <ul class="_img_perfil">
        <li><span class="avatar_mask"><img src="<?php echo getAvatar($MySession->GetVar('id')); ?>"/></span></li>
        <li><a class="_btn _secondary" href="javascript:void(0)" onclick="$('#avatar').click();">Personaliza tu avatar</a></li>
    </ul>
  </div>

  <form id="avatar_form" name="chose_avatar" method='post' action="/admin/users/chose.avatar.php" >
    <ul class="_ul_avatar">
        <?php foreach($avatares_validos as $avatar): ?>
            <li class="_thinks_avatar">
                <label class="label_grabatar">
                    <input class="_check_avatar" type="radio" value="<?php echo $avatar["name"]; ?>" name="avatar" <?php echo ($avatar["status"] == 1 ? "checked='checked'" : ""); ?>>
                    <span class="_img_avatar"><?php echo makeHTMLImg($avatar["url"], 50, 50); ?></span>
                    <span class="_avatar_title"><?php echo $avatar["name"]; ?></span>
                </label>
            </li>
        <?php endforeach; ?>
        <li class="_change_avatar"><input class="_btn _secondary" type="submit" value="Cambiar avatar" /></li>
    </ul>


  </form>

  <form name="frm_avatar" method='post' action="/admin/users/submit.avatar.php" enctype="multipart/form-data">
      <div style="display:none;" class="margin_bottom">
          <input type="file" id="avatar" name="avatar" />
      </div>
  </form>
</div>
</div>
<script >
        $('form[name=frm_avatar] input[name=avatar]').change(function (e) {
            $('form[name=frm_avatar]').submit();
        });
</script>
