<div class="content">
    <div class="w-xxxx-12"><?php echo breadcrumbs(); ?></div>
        <div class="w-xxxx-12 cont_global_admin">
        <h1 class="titulo_seccion_admin">Usuarios</h1>
        <div class="w-xxxx-12 cont_header_panel">
            <div class="_wrapp_form_serch">
                <?php echo $MyFiltrosForm->openTag(); ?>
                <?php echo $MyFiltrosForm->getAllRow(); ?>
                <?php echo $MyFiltrosForm->endTag(); ?>
                <a href="<?php echo $MyRequest->url(FRM_OPERADORES); ?>" class="_btn_new">Nuevo</a>
            </div>
            </div>
            <div  class="w-xxxx-12 cont_gral_admin cont_usuarios_reg">
                <div >
                    <div class="w-xxxx-12">
                        <div class="w-xxxx-12  contenedor_titulo_columnas">
                            <div class="w-xxxx-2"><?php echo makeHTMLOrder( "fecha", "Fecha registro"); ?></div>
                            <div class="w-xxxx-2"><?php echo makeHTMLOrder( "usuario", "Usuario"); ?></div>
                            <div class="w-xxxx-1"><?php echo makeHTMLOrder( "email", "E-mail"); ?></div>
                            <div class="w-xxxx-3"><?php echo makeHTMLOrder( "nombre", "Nombre"); ?></div>
                            <div class="w-xxxx-1"><?php echo makeHTMLOrder( "nivel", "Tipo usuario"); ?></div>
                            <div class="w-xxxx-1">Eliminar</div>
                            <div class="w-xxxx-1">Editar</div>
                            <div class="w-xxxx-1">Contraseña</div>
                        </div>
                        <div class="contenedor_columnas_info"  >
                            <div class="contenedor_columnas"  >
                                 <div class='{{_data.thisClass}} w-xxxx-2'>{{_data.fecha}} &nbsp;</div>
                                <div class='{{_data.thisClass}} w-xxxx-2'>{{_data.usuario}} &nbsp;</div>
                                <div class='{{_data.thisClass}} w-xxxx-1 email'>{{_data.email}} &nbsp;</div>
                                <div class='{{_data.thisClass}} w-xxxx-3'>{{_data.nombre}} &nbsp;</div>
                                <div class='{{_data.thisClass}} w-xxxx-1'>{{_data.nivel}} &nbsp;</div>
                                <div class='{{_data.thisClass}} w-xxxx-1'><a class="btn_adm_eliminar " id="{{_data.id}}" href="#{{_data.nuevo_estado}}" ></a></div>
                                <div class='{{_data.thisClass}} w-xxxx-1'><a class="btn_adm_editar" href="<?php echo $MyRequest->link(FRM_OPERADORES . "?id={{_data.id}}&amp;callback={{_data.callback}}"); ?>"><i class="icon icon-editar"> </i></a></div>
                                <div class='{{_data.thisClass}} w-xxxx-1'><a class="btn_adm_editar_pass" href="<?php echo $MyRequest->link(FRM_PASS_OPERADORES . "?id={{_data.id}}&amp;callback={{_data.callback}}"); ?>"> <i class="icon icon-d-contrasena"> </i></a></div>
                            </div>
                        </div>
                    </div>
                    <div class="w-xxxx-12">
                        <div class="no_hay_datos" >No hay usuarios registrados</div>
                    </div>
                    <div class="w-xxxx-12">
                        <?php echo render("admin/widget.paginar.phtml"); ?>
                    </div>
                </div>
            </div>
    </div>
</div>

<script >
$(".contenedor_columnas_info").htmlDataDum(<?php echo json_encode($lista_admin_data); ?>,".no_hay_datos");

$(window).load(function(){
    $(".btn_adm_eliminar").click(function(event){

         event.preventDefault();
         var nuevo_estado = ($(this).attr("href").replace("#","") == "activar" ? 1 : 0);

         EliminarRegistro('EliminarUser',$(this).attr("id"),nuevo_estado)

     });
 });
</script>

<?php if(!$Mobile_detect->isMobile()): ?>
<script >
$( document ).ready(function() {
 $(function() {
     $( "input[name=rango_inicial]" ).datepicker({
         defaultDate: "+1w",
         changeMonth: false,
         numberOfMonths: 3,
         dateFormat:"yy-mm-dd",
         maxDate: "+0D",
         onClose: function( selectedDate ) {
         $("input[name=rango_final]" ).datepicker( "option", "minDate", selectedDate );
         }
     });
     $( "input[name=rango_final]" ).datepicker({
         defaultDate: "+1w",
         changeMonth: false,
         numberOfMonths: 3,
         dateFormat:"yy-mm-dd",
         maxDate: "+0D",
         onClose: function( selectedDate ) {
         $( "input[name=rango_inicial]").datepicker( "option", "maxDate", selectedDate );
         }
     });
 });
});
</script>
<?php endif; ?>
