<div class="content">
    <div class="w-xxxx-12"><?php echo breadcrumbs(); ?></div>
    <div class="w-xxxx-12 cont_global_admin">
    <h1 class="titulo_seccion_admin">Calificaciones</h1>
    <div class="w-xxxx-12  cont_header_panel">
       <div class="form-group form-inline">
			
			 <?php echo $MyFiltrosForm->openTag(); ?>
                            <?php echo $MyFiltrosForm->getAllRow(); ?>
                            <?php echo $MyFiltrosForm->endTag(); ?>
		</div>
    </div>
    <div  class="w-xxxx-12 cont_gral_admin cont_calificaciones_blog"> 
        <div >
            <div class="w-xxxx-12">
                <div class="w-xxxx-12 contenedor_titulo_columnas">
                    <div class="w-xxxx-3"><?php echo makeHTMLOrder( "calificaciones_blog.fecha", "Fecha"); ?></div>
                    <div class="w-xxxx-3"><?php echo makeHTMLOrder( "titulo", "Articulo"); ?></div>
                   <div class="w-xxxx-3"><?php echo makeHTMLOrder( "calificacion", "Calificacion"); ?></div>
                    <?php if($MyAccessList->MeDasChancePasar(ADMINISTRAR_CALIFICAR_ARTICULOS_BLOG)): ?>
                    <div class="w-xxxx-3"><?php echo makeHTMLOrder( "autor", "Usuario"); ?></div>
                    <?php endif; ?>
                  
                </div>
                <div class="contenedor_columnas_info"   >
                <div class="w-xxxx-12 contenedor_columnas"   >
                    <div class='{{_data.fecha}} w-xxxx-3' >{{_data.fecha}}</div>
                    <div class='{{_data.thisClass}} w-xxxx-3' ><a href="{{_data.link}}">{{_data.titulo}}</a></div>
                    <div class='{{_data.thisClass}} w-xxxx-3' >{{_data.calificacion}}</div>
                    <?php if($MyAccessList->MeDasChancePasar(ADMINISTRAR_CALIFICAR_ARTICULOS_BLOG)): ?>
                   <div class='{{_data.thisClass}} w-xxxx-3' >{{_data.autor}}</div>
                    <?php endif; ?>
                
                </div>
                </div>
            </div>
            <div class="w-xxxx-12">
                <div class="no_hay_datos" >No hay calificaciones registradas</div>
            </div>
           <div class="w-xxxx-12">
                    <?php echo render("admin/widget.paginar.phtml"); ?>
            </div>
        </div>
    </div>
</div>
</div>
<script >
<!--
$(".contenedor_columnas_info").htmlDataDum(<?php echo json_encode($lista_admin_data); ?>,".no_hay_datos");
// -->
</script>

  
