<div class="w-xxxx-12">
    <div class="content">
        <div class="w-xxxx-12">
            <div class="_cont_login_register_acount">
                <h1 class="align_center">Registro</h1>
                <div class="w-xxxx-12">
                    <?php echo $registroForm->openTag(); ?>
                    <?php echo $registroForm->get('token_xsrf'); ?>
                    <?php echo $registroForm->get('callback'); ?>
                    <?php echo $registroForm->getRow('nombre'); ?>
                    <?php echo $registroForm->getRow('usuario'); ?>
                    <?php echo $registroForm->getRow('contrasena'); ?>
                    <?php echo $registroForm->getRow('contrasena1'); ?>
                    <?php echo $registroForm->getRow('email'); ?>
                    <?php echo $registroForm->getRow('telefono'); ?>

                    <?php echo $registroForm->getRow('sexo'); ?>
                    <?php echo $registroForm->getRow('fecha_nacimiento'); ?>
                    <?php echo $registroForm->getRow('acepto'); ?>
                    <label id="acepto-error" class="error" for="acepto" style="display:none;"></label>
                    <div class="_tag_center">
                      <?php echo $registroForm->getRow('guardar'); ?>
                    </div>
                    <?php echo $registroForm->endTag(); ?>
                </div>
                <div class="w-xxxx-12 _space_border">
                    <h2 class="align_center">¿Ya tienes una cuenta?</h2>
                    <div class="_tag_center">
                      <a class="_btn _secondary" href="<?php echo $MyRequest->url(LOGIN); ?>">Inicia sesión</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>