<div class="content">
    <div class="w-xxxx-12"><?php echo breadcrumbs(); ?></div>
    <div class="w-xxxx-12 cont_global_admin">
    <h1 class="titulo_seccion_admin">Comentarios</h1>
    <div class="w-xxxx-12  cont_header_panel">
       <div class="form-group form-inline">

            <?php echo $MyFiltrosForm->openTag(); ?>
               <?php echo $MyFiltrosForm->getAllRow(); ?>
               <?php echo $MyFiltrosForm->endTag(); ?>
		</div>
    </div>
    <div  class="w-xxxx-12 cont_gral_admin cont_comentarios_blog">
        <div >
            <div class="w-xxxx-12">
                <div class="w-xxxx-12 contenedor_titulo_columnas">
                    <div class="w-xxxx-2"><?php echo makeHTMLOrder( "comentarios_blog.fecha", "Fecha"); ?></div>
                    <div class="w-xxxx-3"><?php echo makeHTMLOrder( "blog.titulo", "Articulo"); ?></div>
                   <div class="w-xxxx-3"><?php echo makeHTMLOrder( "comentario", "Comentario"); ?></div>
                    <?php if($MyAccessList->MeDasChancePasar(ADMINISTRAR_COMENTARIOS_ARTICULOS_BLOG)): ?>
                    <div class="w-xxxx-3"><?php echo makeHTMLOrder( "autor", "Usuario"); ?></div>
                    <div class="w-xxxx-1">Eliminar</div>
                    <?php endif; ?>

                </div>
                <div class="contenedor_columnas_info"   >
                <div class="w-xxxx-12  contenedor_columnas"   >
                    <div class='{{_data.fecha}} w-xxxx-2' >{{_data.fecha}}</div>
                    <div class='{{_data.thisClass}} w-xxxx-3' ><a href="{{_data.link}}">{{_data.titulo}}</a></div>
                    <div class='{{_data.thisClass}} w-xxxx-3' >{{_data.comentario}}</div>
                    <?php if($MyAccessList->MeDasChancePasar(ADMINISTRAR_COMENTARIOS_ARTICULOS_BLOG)): ?>
                    <div class='{{_data.thisClass}} w-xxxx-3' >{{_data.autor}}{{_data.nombre}}</div>

                    <div class='{{_data.thisClass}} w-xxxx-1'>
                    <a class="btn_adm_eliminar" id="{{_data.id}}" href="#{{_data.nuevo_estado}}" ></a>
                    </div>
                    <?php endif; ?>

                </div>
                </div>
            </div>
            <div class="w-xxxx-12">
                <div class="no_hay_datos" >No hay comentarios registrados</div>
            </div>
           <div class="w-xxxx-12">
                    <?php echo render("admin/widget.paginar.phtml"); ?>
                </div>
        </div>
    </div>
</div>
</div>
<script >

$(".contenedor_columnas_info").htmlDataDum(<?php echo json_encode($lista_admin_data); ?>,".no_hay_datos");
$(window).load(function(){
    $(".btn_adm_eliminar").click(function(event){

         event.preventDefault();
         var nuevo_estado = ($(this).attr("href").replace("#","") == "activar" ? 1 : 0);

         <?php if(getCoreConfig('blog/registers/showdelete') == 0): ?>      
                EliminarRegistro('EliminarComentarioBlog',$(this).attr("id"),nuevo_estado,'','EliminarRegistorPanelRemove')
        <?php else: ?>
                EliminarRegistro('EliminarComentarioBlog',$(this).attr("id"),nuevo_estado)
         <?php endif; ?>

     });
 });


</script>
