<div class="w-xxxx-12">
	<div class="cont_success_oxxo">
		<div class="w-xxxx-10">
			<h2><i class="icon icon-valido"></i> Gracias por realizar tu orden.</h2>
			<p>Da click en "TERMINAR COMPRA" y en breve recibirás un correo electrónico con tu  referencia númerica la cual deberás presentar en alguno de los
				siguientes establecimientos para realizar tu pago.</p>
			<ul>
		    <li><?=makeHTMLImg("/public/skin/ecommerce/images/openpay/01.png",100,50)?></li>
		     <li><?=makeHTMLImg("/public/skin/ecommerce/images/openpay/02.png",100,50)?></li>
          <li><?=makeHTMLImg("/public/skin/ecommerce/images/openpay/03.png",100,50)?></li>
           <li><?=makeHTMLImg("/public/skin/ecommerce/images/openpay/04.png",100,50)?></li>
            <li><?=makeHTMLImg("/public/skin/ecommerce/images/openpay/05.png",100,50)?></li>
             <li><?=makeHTMLImg("/public/skin/ecommerce/images/openpay/06.png",100,50)?></li>
              <li><?=makeHTMLImg("/public/skin/ecommerce/images/openpay/07.png",100,50)?></li>
               <li><?=makeHTMLImg("/public/skin/ecommerce/images/openpay/08.png",100,50)?></li>
	    </ul>
			<span>
				<a class="_btn _btn-primary" href="<?=$MyRequest->url(CONFIRMACION_OPENPAY_ESTABLECIMIENTO)?>?establecimiento_pay=<?=$token?>">Terminar compra</a>
			</span>
		</div>
		<div class="w-xxxx-2">
				<a href="javascript:void(0)" onclick="changePaimentMethod();"><i class="icon icon-editar"></i> Cambiar</a>
		</div>
	</div>
</div>
