<script>
$("#card-form").find("input[type=submit]").prop("disabled", true);
$("form[name=frm_tarjeta_checkout] input[name=continuar]").prop("disabled", true);
var openpaySuccessResponseHandler = function(response) {
   var $form = $("#card-form");
   $form.append($("<input name=\"token\" type=\"hidden\">").val(response.data.id));
   console.log(response);
   $form.get(0).submit();
};

var openpayErrorResponseHandler = function(response) {
   var desc = response.data.description != undefined ? response.data.description : response.message;
   var $form = $("#card-form");
   console.log(response);
   _alert("ERROR [" + response.status + "] " + desc);
   $form.find("input[type=submit]").prop("disabled", false);
   return false;
};

$("input[name=id_tarjeta]").change(function()
{
    if($(this).val() == 0)
    {
        $("#form_new_card").show();
        $("form[name=frm_tarjeta_checkout] input[name=continuar]").hide();
    }
    else
    {
        $("#form_new_card").hide();
        $("form[name=frm_tarjeta_checkout] input[name=continuar]").show();
    }
});

var validacionesOpenpay  = function(){
      $("form[name=card-form]").validate({
        ignore: [],
          rules: {

              'holder_name': {
                 required: true,
              },
              'card_number': {
                 required: true,
              //   minlength: 12,
                //  maxlength: 12
              },
              'cvv2': {
                  required: true,
                  minlength:3,
                  maxlength: 3
              },
              'expiration_month': {
                  required: true
              },
              'expiration_year': {
                  required: true
              }

          },
          messages: {

              'holder_name': {
                  required: "Favor de escribir el nombre de la tarjeta"
              },
              'card_number': {
                  required: "Favor de escribir el n&uacute;mero de la tarjeta",
                  minlength: "El n&uacute;mero de tarjeta debe tener 12 numeros",
                  maxlength: "El n&uacute;mero de tarjeta debe tener 12 numeros",
              },
              'cvv2': {
                 required: "Favor de escribir el n&uacute;mero de seguridad",
                  minlength: "El n&uacute;mero de seguridad debe tener 3 numeros",
                  maxlength: "El n&uacute;meros de seguridad debe tener 3 numeros",
              },
               'expiration_month': {
                 required: "Favor de seleccionar el mes de expiraci&oacute;n",
              },
              'expiration_year': {
                 required: "Favor de seleccionar el a&ntilde;o de expiraci&oacute;n"
              },

          },

           invalidHandler: function(event, validator) {


            },
          submitHandler: function() {

              OpenPay.setId('<?php echo (getCoreConfig('ecommerce/openpay/sandbox') == 1 ? getCoreConfig('ecommerce/openpay/idsandbox') :  getCoreConfig('ecommerce/openpay/id')); ?>');
              OpenPay.setApiKey('<?php echo (getCoreConfig('ecommerce/openpay/sandbox') == 1 ? getCoreConfig('ecommerce/openpay/publicsandbox') :  getCoreConfig('ecommerce/openpay/public')); ?>');
              OpenPay.setSandboxMode(<?=(bool)getCoreConfig('ecommerce/openpay/sandbox')?>);

              //jQuery generate the token on submit.

              var $form = $("form[name=card-form]");
              // Prevents double clic
              var deviceSessionId = OpenPay.deviceData.setup("card-form", "device_session_id");
              $form.find("input[type=submit]").prop("disabled", true);
              
              OpenPay.token.extractFormAndCreate('card-form', openpaySuccessResponseHandler, openpayErrorResponseHandler);
              
              return false;

          },
          onkeyup: false,
          errorClass: "error invalid-input",
          validClass: "valid-input"

      });
      
    $("form[name=frm_tarjeta_checkout]").validate({
    ignore: [],

      submitHandler: function() {

        OpenPay.setId('<?php echo (getCoreConfig('ecommerce/openpay/sandbox') == 1 ? getCoreConfig('ecommerce/openpay/idsandbox') :  getCoreConfig('ecommerce/openpay/id')); ?>');
        OpenPay.setApiKey('<?php echo (getCoreConfig('ecommerce/openpay/sandbox') == 1 ? getCoreConfig('ecommerce/openpay/publicsandbox') :  getCoreConfig('ecommerce/openpay/public')); ?>');
        OpenPay.setSandboxMode(<?=(bool)getCoreConfig('ecommerce/openpay/sandbox')?>);
        //jQuery generate the token on submit.
        var $form = $("form[name=frm_tarjeta_checkout]");
        // Prevents double clic

       
        var deviceSessionId = OpenPay.deviceData.setup("frm_tarjeta_checkout", "device_session_id");
        return true;
      }

  });
};

importarScript('https://openpay.s3.amazonaws.com/openpay.v1.min.js',function(){
    importarScript('https://openpay.s3.amazonaws.com/openpay-data.v1.min.js',function(){
        $("#card-form").find("input[type=submit]").prop("disabled", false);
        $("form[name=frm_tarjeta_checkout] input[name=continuar]").prop("disabled", false);
        validacionesOpenpay()
    });
});
</script>
