<div class="content">
    <div class="w-xxxx-12"><?php echo breadcrumbs(); ?></div>
    <div class="w-xxxx-12">
        <div class="w-xxxx-5 m-r-xxxx-1 change_float_right">
            <h2><?=$title_form?></h2>
            <ul class="_ul_default">
                <li>Aqui descripcion</li>
            </ul>
        </div>
         <div class="w-xxxx-4 m-l-xxxx-1 change_float_left">
        <?php echo $adminForm->openTag(); ?>
        <?php echo $adminForm->getRow('callback'); ?>
        <?php if(!empty($id)): ?>
        <?php echo $adminForm->getRow('id'); ?>
        <?php endif; ?>

        <?php echo $adminForm->getRow('name'); ?>
        
        <?php echo $adminForm->getRow('description'); ?>

        <?php echo $adminForm->getRow('visible_in_search'); ?>
        <?php echo $adminForm->getRow('users[]'); ?>
        <div id="imagen_previa">
            <?php if(!empty($data['image'])): ?>
              <?=makeHTMLImg($data['image'], "", "", "");?>
            <?php endif; ?>
        </div>
        <?php echo $adminForm->getRow('image'); ?>
        <div class="form-group"><h3>SEO</h3></div>
        <?php echo $adminForm->getRow('url_key'); ?>
        <?php echo $adminForm->getRow('meta_title'); ?>
        <?php echo $adminForm->getRow('meta_description'); ?>
        <?php echo $adminForm->getRow('meta_keywords'); ?>
        <?php echo $adminForm->getRow('guardar'); ?>
        <?php echo $adminForm->endTag(); ?>
        </div>
    </div>
</div>
<script >
$(document).ready(function(){
         $("#frmcategoria").validate();
         $('textarea[name=meta_keywords]').tagsInput({width:'auto'});
});
$('#image_category').change(function(){
    if (this.files && this.files[0])
    {
        var reader = new FileReader();
        reader.onload = function (e)
        {
            $('#imagen_previa').html('<img style="width: 150px" src="'+e.target.result+'" alt="Preview" />');
        }
        reader.readAsDataURL(this.files[0]);
    }
});
</script>