<div class="w-xxxx-12">
    <div class="content">
        <h1>Empresa</h1>
        <div class="w-xxxx-6">
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias dolores ratione consectetur cum qui aut, recusandae temporibus placeat, ad, ipsa nisi eligendi illo quos. Nesciunt quae hic natus expedita atque consequatur aspernatur quis et eligendi tempora sit fugit corporis, id at optio, quia vero quod aliquam eum, suscipit deserunt pariatur neque? Nulla saepe ipsam pariatur aut reiciendis. Veniam dignissimos a maxime omnis voluptatem ipsa non beatae numquam, doloribus alias aperiam et sit molestias laudantium animi ipsam sed. Labore, quaerat repellat! Maxime culpa ut itaque perferendis deserunt distinctio. Quaerat nemo atque harum? Animi mollitia nostrum eveniet ex voluptas possimus aut libero dolores? Aut voluptas adipisci eaque esse voluptatum tenetur pariatur quia quisquam. Vel sapiente velit molestiae id a quia distinctio facilis.
            </p>
            </div>
            <div class="w-xxxx-6">
            <p>
                <?php echo makeHTMLImg(getImg('home/quienes_1.jpg'),"","","","class='image_100'"); ?>
            </p>
        </div>
    </div>
</div>
