<div class="content">
    <div class="w-xxxx-12"><?php echo breadcrumbs(); ?></div>
    <div class="w-xxxx-12 cont_global_admin">
        <h1 class="titulo_seccion_admin">Contacto</h1>
        <div class="w-xxxx-12 cont_header_panel">
             <div class="_wrapp_form_serch">
                <?php echo $MyFiltrosForm->openTag(); ?>
                <?php echo $MyFiltrosForm->getAllRow(); ?>
                <?php echo $MyFiltrosForm->endTag(); ?>
                <a href="/admin/contacto/excel.php?busca_b=<?php echo $busca_b; ?>&amp;rango_inicial=<?php echo $rango_inicial; ?>&amp;rango_final=<?php echo $rango_final; ?>" target="_blank" class="_btn_new">Exportar</a>

            </div>
        </div>

        <div  class="w-xxxx-12 cont_gral_admin cont_contactos">
            <div >
                <div class="w-xxxx-12">
                    <div class="w-xxxx-12 contenedor_titulo_columnas">
                        <div class="w-xxxx-2"><?php echo makeHTMLOrder( "fecha", "Fecha"); ?></div>
                        <div class="w-xxxx-4"><?php echo makeHTMLOrder( "nombre", "Nombre"); ?></div>
                        <div class="w-xxxx-1"><?php echo makeHTMLOrder( "email", "E-mail"); ?></div>
                        <div class="w-xxxx-1"><?php echo makeHTMLOrder( "telefono", "Telefono"); ?></div>
                        <div class="w-xxxx-3"><?php echo makeHTMLOrder( "asunto", "Asunto"); ?></div>
                        <div class="w-xxxx-1">Eliminar</div>
                    </div>
                    <div class="contenedor_columnas_info"  >
                    <div class="contenedor_columnas" id="content_row_{{_data.id}}" >
                        <div class='w-xxxx-2'>{{_data.fecha}}</div>
                        <div class='w-xxxx-4'>{{_data.nombre}}</div>
                        <div class='w-xxxx-1 email'>{{_data.email}}</div>
                        <div class='w-xxxx-1 telephone'>{{_data.telefono}}</div>
                        <div class='w-xxxx-3'>{{_data.asunto}}</div>
                        <div class='w-xxxx-1 _table_delete {{_data.thisClass}}'>
                            <a class="btn_adm_eliminar" id="{{_data.id}}" href="#{{_data.nuevo_estado}}" ></a>
                        </div>
                        <div class='w-xxxx-12 _open_comment'>
                            <a href="javascript:void(0);" onclick="$(this).next('div').toggle('slow'); $(this).parent('div').toggleClass('active');">Ver comentario</a>
                            <div style="display:none;">
                            {{_data.comentario}}
                            </div>
                        </div>
                    </div>
                    </div>
                </div>
                <div class="w-xxxx-12">
                    <div class="no_hay_datos" >No hay informacion de contacto registrada</div>
                </div>
                <div class="w-xxxx-12">
                    <?php echo render("admin/widget.paginar.phtml"); ?>
                </div>
            </div>
        </div>
    </div>
</div>
<script >
$(".contenedor_columnas_info").htmlDataDum(<?php echo json_encode($lista_admin_data); ?>,".no_hay_datos");
$(window).load(function(){
    $(".btn_adm_eliminar").click(function(event){

         event.preventDefault();
         var nuevo_estado = ($(this).attr("href").replace("#","") == "activar" ? 1 : 0);

         EliminarRegistro('<?php echo $deleteFunction; ?>',$(this).attr("id"),nuevo_estado,"","EliminarRegistorPanelRemove")

    });


});
</script>

<?php if(!$Mobile_detect->isMobile()): ?>
<script >
$( document ).ready(function() {
 $(function() {
     $( "input[name=rango_inicial]" ).datepicker({
         defaultDate: "+1w",
         changeMonth: false,
         numberOfMonths: 3,
         dateFormat:"yy-mm-dd",
         maxDate: "+0D",
         onClose: function( selectedDate ) {
         $("input[name=rango_final]" ).datepicker( "option", "minDate", selectedDate );
         }
     });
     $( "input[name=rango_final]" ).datepicker({
         defaultDate: "+1w",
         changeMonth: false,
         numberOfMonths: 3,
         dateFormat:"yy-mm-dd",
         maxDate: "+0D",
         onClose: function( selectedDate ) {
         $( "input[name=rango_inicial]").datepicker( "option", "maxDate", selectedDate );
         }
     });
 });
});
</script>
<?php endif; ?>
