<div class="_card_widget_catalog_product_result">
    <?=render(PROJECT_DIR.'/modulos/wishlist/diseno/widget.wishlist.phtml',['id' =>$data['id_wishlist'],'seccion' => 'catalog_products'])?>
    <a href="<?= $data['link']; ?>" class="_img_widget_catalog_product_result"><?php echo makeHTMLImg($data['thumb_resize'],"","",$data['name'],"class='image_100'"); ?></a>
    <h2 class="_h2_widget_catalog_product_result"><a href="<?= $data['link']; ?>" ><?=$data['name']?></a></h2>
    <span class="price"><?=getFormatoPrecio($data['price'],false)?></span>
    <a class="_btn _widget_catalog_view_more" href="<?= $data['link']; ?>">Ver detalles</a>
</div>
