<div class="w-xxxx-12">
    <div class="content">
        <div class="w-xxxx-12 cont_search_bar">
        <?=getCatalogBuscadorPrincipal()?>
        </div>
        <div class="w-xxxx-12">
            <div class="cont_widget_catalog_filter">
                <h3>Filtros</h3>
            </div>
            <div class="cont_widget_catalog_results">
                <div class="_card_widget_catalog_product_result">
                    <a class="_widget_catalog_add_wishlist" href="javascript:void(0);"></a>
                    <a href="http://local.franky/productos/detalle/" class="_img_widget_catalog_product_result"><?php echo makeHTMLImg(getImg('demo/tshirt.jpg'),"","","","class='image_100'"); ?></a>
                    <h2 class="_h2_widget_catalog_product_result"><a href="http://local.franky/productos/detalle/" >Nombre del producto</a></h2>
                    <span class="price">Precio</span>
                    <a class="_btn _widget_catalog_view_more" href="http://local.franky/productos/detalle/">Ver detalles</a>
                </div>
                <div class="_card_widget_catalog_product_result">
                    <a class="_widget_catalog_add_wishlist" href="javascript:void(0);"></a>
                    <a href="http://local.franky/productos/detalle/" class="_img_widget_catalog_product_result"><?php echo makeHTMLImg(getImg('demo/tshirt2.jpg'),"","","","class='image_100'"); ?></a>
                    <h2 class="_h2_widget_catalog_product_result"><a href="http://local.franky/productos/detalle/" >Nombre del producto</a></h2>
                    <span class="price">Precio</span>
                    <a class="_btn _widget_catalog_view_more" href="http://local.franky/productos/detalle/">Ver detalles</a>
                </div>


            </div>
        </div>
    </div>
</div>
