<div class="w-xxxx-12 _catalog_result">
    <div class="content">
    <?=CatalogBreadcrumbs(null); ?>
        <?php if(isset($image_category['img']) &&  !empty($image_category['img'])): ?>
        <?= makeHTMLImg($image_category['img'], "", "", "","class='image_100'")?>
        <?php endif; ?>
        
        <div class="w-xxxx-12">
            <?php if(getCoreConfig('catalog/product/buscadorlateral') == 1):?>
            <div class="cont_widget_catalog_filter">
                <h3>Filtros</h3>

                <?=catalog_getBuscadorLateral()?>
            </div>
            <?php endif; ?>
            <div class="cont_widget_catalog_results <?=(getCoreConfig('catalog/product/buscadorlateral') == 1 ? '' : '_no_filters')?>">
            
            <div class="w-xxxx-12">
            <?php if(!empty($q)): ?>
                <h2 class="resultados_q">Resultados de busqueda para la palabra <strong>"<?=$q?>"</strong></h2>
            <?php endif; ?>
            <?php if(isset($image_category['description']) && !empty($image_category['description'])): ?>
            <p class="landing_producto_descripcion"><?= $image_category['description']?></p>
            <?php endif; ?>
            </div>
                <?php if(!empty($resultados_pagina)): ?>
                    <?php foreach($resultados_pagina as $data): ?>
                        <?=render('products/card.phtml',['data' => $data]);?>
                    <?php endforeach ;?>
                    <div class="w-xxxx-12 cont-paginar"><?php echo render("widget.paginar.phtml"); ?></div>
                    <?php echo $itemListSchema->get(); ?>
                <?php else: ?>
                    <h2>No se encontraron productos</h2>
                    <p>Intenta con otros términos de búsqueda.</p>
                <?php endif; ?>


            </div>
        </div>
    </div>
</div>
