<div class="w-xxxx-12 _catalog_result">
    <div class="content">
        <?php if(!empty($image_category)): ?>
        <?= makeHTMLImg($image_category, "", "", "","class='image_100'")?>

        <?php endif; ?>
        <div class="w-xxxx-12">
            <?php if(getCoreConfig('catalog/product/buscadorlateral') == 1):?>
            <div class="cont_widget_catalog_filter">
                <h3>Filtros</h3>

                <?=catalog_getBuscadorLateral()?>
            </div>
            <?php endif; ?>
            <div class="cont_widget_catalog_results <?=(getCoreConfig('catalog/product/buscadorlateral') == 1 ? '' : '_no_filters')?>">
                <?php if(!empty($resultados_pagina)): ?>
                    <?php foreach($resultados_pagina as $data): ?>
                        <?=render('products/card.phtml',['data' => $data]);?>
                    <?php endforeach ;?>
                    <div class="w-xxxx-12 cont-paginar"><?php echo render("widget.paginar.phtml"); ?></div>
                    <?php echo $itemListSchema->get(); ?>
                <?php else: ?>
                    <h2>No se encontraron productos</h2>
                    <p>Intenta con otros términos de búsqueda.</p>
                <?php endif; ?>


            </div>
        </div>
    </div>
</div>
