<div class="w-xxxx-12">
    <div class="content">
        <div class="w-xxxx-12 cont_search_bar">
            <?=getCatalogBuscadorPrincipal()?>
        </div>
        <div class="w-xxxx-12">
            <div class="content">
                <div class="w-xxxx-6">
                    <?=render("products/widget.images.phtml",['data_detalle' => $data_detalle,'MyConfigure' => $MyConfigure])?>
                   
                 
                </div>
                <div class="w-xxxx-6">
                    <h1><?=$data_detalle['name']?></h1>
                    <div>SKU: <?=$data_detalle['sku']?></div>
                    <div>Stock: <?=$data_detalle['stock']?></div>
                    <h2>Descripcion</h2>
                    <div><?=$data_detalle['description']?></div>
                    <div class="w-xxxx-12 ">
                    <div class="w-xxxx-12 align_center">
                        <a href="javascript:void(0);" data-idlove="<?= $data_detalle['id']; ?>" class="ilove"> <span>Guardar favorito</span></a>
                    </div>
                    <div class="precio">
                        <?php echo getFormatoPrecio($data_detalle['price'],false); ?>
                    </div>
                    <div style="border:solid 1px #E7E7E7;" class="align_center">
                        <?php echo render(PROJECT_DIR.'/modulos/catalog/diseno/ecommerce/boton.add.phtml',
                        array("id_producto" => $data_detalle["id"],
                        "in_stock" => $data_detalle["in_stock"],
                        "min_qty" => $data_detalle["min_qty"],
                        "saleable" => $data_detalle["saleable"],
                        "stock" => $data_detalle["stock"],
                        "stock_infinito" => $data_detalle["stock_infinito"],
                        'MyAccessList' => $MyAccessList,
                        'contactanosForm' => $contactanosForm)); ?>
                    </div>
                    </div>
                </div>

            </div>
        </div>

    </div>
</div>

<script>
  $(document).ready(function(){
        $('[data-idlove]').click(function(){
            catalog_addWishlist($(this).attr('data-idlove'),($(this).attr('class').search('active') > -1 ? 0 : 1));
        });
        catalog_getWishlist();
  });
</script>
