<div class="w-xxxx-12 _product_view">
    <div class="content">
        <div class="w-xxxx-12 cont_search_bar_ecommerce">
            <?=getCatalogBuscadorPrincipal()?>
        </div>
        <div class="w-xxxx-12">
            <div class="content">
                <div class="w-xxxx-6 _catalog_gallery">
                    <?=render("products/widget.images.phtml",['data_detalle' => $data_detalle,'MyConfigure' => $MyConfigure])?>
                </div>
                <div class="w-xxxx-6 _product_info">
                    <h1 class="_name"><?=$data_detalle['name']?></h1>
                    <span class="_sku">SKU: <?=$data_detalle['sku']?></span>
                    <span class="_stock">Stock: <?=$data_detalle['stock']?></span>
                    <span class="_price"><?php echo getFormatoPrecio($data_detalle['price'],false); ?></span>
                    <div class="_cont_more_info">
                        <a href="javascript:void(0);" data-idlove="<?= $data_detalle['id']; ?>" class="_btn _btn-default ilove _btn_whislist"> <span>Guardar como favorito</span></a>
                        <?php echo render(PROJECT_DIR.'/modulos/catalog/diseno/ecommerce/boton.add.phtml',
                        array("id_producto" => $data_detalle["id"],
                        "in_stock" => $data_detalle["in_stock"],
                        "min_qty" => $data_detalle["min_qty"],
                        "saleable" => $data_detalle["saleable"],
                        "stock" => $data_detalle["stock"],
                        "stock_infinito" => $data_detalle["stock_infinito"],
                        'MyAccessList' => $MyAccessList,
                        'contactanosForm' => $contactanosForm)); ?>
                    </div>
                    <h2>Descripcion</h2>
                    <div class="_description"><?=$data_detalle['description']?></div>
                </div>

            </div>
        </div>

    </div>
</div>

<script>
  $(document).ready(function(){
        $('[data-idlove]').click(function(){
            catalog_addWishlist($(this).attr('data-idlove'),($(this).attr('class').search('active') > -1 ? 0 : 1));
        });
        catalog_getWishlist();
  });
</script>
