<div class="w-xxxx-12">
    <div class="content">
        <h1 class="align_center"></h1>
        <h3 class="align_center"></h3>
        <?php echo $adminForm->openTag(); ?>
        <?php  echo $adminForm->get("callback"); ?>


        <?php if(!empty($id)): ?>
        <?php  echo $adminForm->get("id"); ?>
        
          <?php  endif; ?>
        <?php  echo $adminForm->getRow("nombre"); ?>
        <?php  echo $adminForm->getRow("code"); ?>

       

        <?php  echo $adminForm->getRow("dots"); ?>
        <?php  echo $adminForm->getRow("auto"); ?>
        <?php  echo $adminForm->getRow("infinito"); ?>
        <?php  echo $adminForm->getRow("visible"); ?>
        <?php  echo $adminForm->getRow("scroll"); ?>
        

        <div class="content_info_responsivo">
      
                
                <div class="w-xxxx-12 content_tab" id="options_attr">
                    <div class="w-xxxx-12" >
                    <div class="w-xxxx-3">Width</div>
                    <div class="w-xxxx-3">visible</div>
                    <div class="w-xxxx-3">scroll</div>
                    </div>
                    
                    <div class="w-xxxx-12 option_list">
                        <div class="w-xxxx-12 opt_1" >
                            <div class="w-xxxx-3"><?php echo $adminForm->get('_width[]'); ?></div>
                            <div class="w-xxxx-3"><?php echo $adminForm->get('_visible[]'); ?></div>
                            <div class="w-xxxx-3"><?php echo $adminForm->get('_scroll[]'); ?></div>
                        </div>
                      
                       
                    </div>   
                    <div class="w-xxxx-12" >
                        <a href="#" class="add_option">Agregar opcion</a>
                    </div>
                </div>
        </div>

        <?php  echo $adminForm->getRow("guardar"); ?>

        <?php echo $adminForm->endTag(); ?>

    </div>

  

</div>



<script >
$(document).ready(function()
{
  $( "#frmcarrucel" ).validate();


  $('.add_option').click(function(e){
             e.preventDefault();
             $('.option_list').append('<div class="w-xxxx-12 opt_'+($('.option_list').children().length+1)+'" >\
                            <div class="w-xxxx-3"><?php echo $adminForm->get('_width[]'); ?></'+'div>\
                            <div class="w-xxxx-3"><?php echo $adminForm->get('_visible[]'); ?>\</'+'div>\
                            <div class="w-xxxx-3"><?php echo $adminForm->get('_scroll[]'); ?>\
                            <a href="javascript:void(0);" onclick="$(\'.opt_'+($('.option_list').children().length+1)+'\').remove();">[X]</'+'a>\
                            </'+'div>\
                            </'+'div>');
         });
         
        <?php  
        $count_option = 1;
        if(!empty($data['responsivo'])): 
            foreach($data['responsivo'] as $k=> $v):
            
                if($count_option > 1): ?>
                    $('.add_option').click();
                <?php endif; ?>
                    
                $('.opt_<?= $count_option ?>').find('input[name="_width[]"]').val('<?=$v['width']?>');
                $('.opt_<?= $count_option ?>').find('input[name="_visible[]"]').val('<?=utf8_decode($v['visible'])?>');
                $('.opt_<?= $count_option ?>').find('input[name="_scroll[]"]').val('<?=utf8_decode($v['scroll'])?>');
        
        <?php 
                $count_option++;
            endforeach;
        
        endif;
        ?>
});
</script>