<div class="w-xxxx-12">
	<div class="cont_success_oxxo">
		<div class="w-xxxx-10">
			<h2><i class="icon icon-valido"></i> Gracias por realizar tu orden.</h2>
			<p>Da click en "TERMINAR COMPRA" y en breve recibirás un correo electrónico con tu  referencia númerica la cual deberás presentar para hacer tu deposito.</p>
			
			<span>
				<a class="_btn _btn-primary" href="<?=$MyRequest->url(CONFIRMACION_SRPAGO_SPEI)?>?spei_srpago=<?=$token?>">Terminar compra</a>
			</span>
		</div>
		<div class="w-xxxx-2">
				<a href="javascript:void(0)" onclick="changePaimentMethod();"><i class="icon icon-editar"></i> Cambiar</a>
		</div>
	</div>
</div>
