<div class="w-xxxx-12 _cont_orden">
    <div class="content">
        <h1>Orden <span>#<?=$pedido?></span></h1>
    </div>
</div>

<iframe  name="frameticket" id="frameticket" frameborder="0" src="/ecommerce/srpago/ticket.php?url=<?=urlencode($referencia['url'])?>" width="100%"
    height="500"  style="min-height:70vh !important;"></iframe>


<div class="action_success">
    <a href="#" class="imprimir_ticket" >Imprimir</a>
    <a href="<?php echo $MyRequest->url(ADMIN_DETALLE_PEDIDOS); ?>?id=<?= $Tokenizer->token('pedidos',$pedido)?>" class="ver_pedido">Ver pedido</a>
    <a href="<?=$MyRequest->url(HOME)?>" class="seguir_comprando">Seguir comprando</a>
</div>


<script>
  $('.imprimir_ticket').click(function(e){
          e.preventDefault();
          window.frames["frameticket"].focus();
          window.frames["frameticket"].print();
  });
</script>