<div class="w-xxxx-12">
	<div class="cont_success_oxxo">
		<div class="w-xxxx-10">
			<h2><i class="icon icon-valido"></i> Gracias por realizar tu orden.</h2>
			<p>En breve recibirás un correo electrónico con tu  referencia númerica la cual deberás presentar en cualquier sucursal OXXO del país para realizar tu pago.</p>
			<p>Tu pago se acreditará a tu cuenta en tiempo real. Recuerda que Oxxo cobrará una comisión de $10 al momento de realizar el cargo.</p>
			<span>
				<a class="_btn _btn-primary" href="<?=$MyRequest->url(CONFIRMACION_CONEKTA_OXXO)?>?token_oxxo=<?=$token?>">Terminar compra</a>
			</span>
		</div>
		<div class="w-xxxx-2">
				<a href="javascript:void(0)" onclick="changePaimentMethod();"><i class="icon icon-editar"></i> Cambiar</a>
		</div>
	</div>
</div>
