<div class="content">
    <div class="w-xxxx-12"><?php echo breadcrumbs(); ?></div>
    <div class="w-xxxx-12">
        <div class="w-xxxx-5 m-r-xxxx-1 change_float_right">
            <h2><?=$title_form?></h2>
            <ul class="_ul_default">
                <li>Aqui descripcion</li>
            </ul>
        </div>
         <div class="w-xxxx-4 m-l-xxxx-1 change_float_left">
        <?php echo $adminForm->openTag(); ?>
        <?php echo $adminForm->getRow('callback'); ?>
        <?php if(!empty($id)): ?>
        <?php echo $adminForm->getRow('id'); ?>
        <?php endif; ?>

        <?php echo $adminForm->getRow('name'); ?>
        <?php echo $adminForm->getRow('label'); ?>
        <?php echo $adminForm->getRow('entity'); ?>

        <?php echo $adminForm->getRow('type'); ?>
        <?php echo $adminForm->getRow('source'); ?>
       
        <?php echo $adminForm->getRow('guardar'); ?>
        <?php echo $adminForm->endTag(); ?>
        </div>
    </div>
</div>
<script >
$(document).ready(function(){
         $("#frmattributes").validate();
});
</script>