<noscript id="deferred-styles">
<?php echo render("admin/layout/css.phtml"); ?>
    <?php echo $MyMetatag->getCss(); ?>
</noscript>
<script >
    <!--
    var loadDeferredStyles = function() {
        var addStylesNode = document.getElementById("deferred-styles");
        var replacement = document.createElement("div");
        replacement.innerHTML = addStylesNode.textContent;
        document.body.appendChild(replacement)
        addStylesNode.parentElement.removeChild(addStylesNode);
    };
    
    var raf = requestAnimationFrame || mozRequestAnimationFrame ||
     webkitRequestAnimationFrame || msRequestAnimationFrame;
    if (raf) raf(function() { window.setTimeout(loadDeferredStyles, 0); });
    else wndow.addEventListener('load', loadDeferredStyles);
   //   -->
</script>