<!DOCTYPE html>
<html lang="<?php echo $lang_root; ?>">
<head>
   <?php  include(getVista("admin/layout/widget.headers.phtml")); ?>
</head>
<body class="<?php echo $MyRequest->getClassBody($lang_root); ?>" <?php echo (!$MyRequest->isAjax() ? 'style="overflow: hidden;"' : ''); ?>>
    <div class="content">
        <?php if(!$MyRequest->isAjax()): ?>
        <div id="preloaderfullpage" style="position: fixed;top:0;left:0;right:0; bottom:0;background: #fff;z-index: 100;">
            <div id="loader" style="width: 100px;height: 100px;position: absolute;left:50%; top:50%;background: url('<?php echo getImg('loader.gif'); ?>') no-repeat center 0; margin:-50px 0 0 -50px;">&nbsp;</div>
        </div>
        <?php endif; ?>
        <main>
        	<div class="w-xxxx-12 page_wrapper">
                <div class="w-xxxx-12 cont_admin">
                    <div class="_left_menu">
                        <?php $logopanel = getImg('logo.png'); ?>

                        <?php
                        if(getCoreConfig('base/theme/logopanel') != "")
                        {
                            if(file_exists(PROJECT_DIR.getCoreConfig('base/theme/logopanel')))
                            {
                                $logopanel = getCoreConfig('base/theme/logopanel');
                            }
                            
                        } 
                        ?>

                        <a class="_admin_logo" href="/"><?php echo makeHTMLImg($logopanel,"","200","200","class='img_logo'"); ?></a>
                        <a class="_my_account" href="<?php echo $MyRequest->url(ADMIN) ?>">Inicio</a>
                        <ul class="_img_perfil">
                            <li><span class="avatar_mask"><?php echo makeHTMLImg(getAvatar($MySession->GetVar('id'))); ?></span></li>
                            <li><a class="_btn _editar_avatar" href="<?=$MyRequest->url(ADMIN_AVATAR); ?>">Editar</a></li>
                        </ul>
                       <?php
                       echo $MyMenuAdmin->getMenu();
                       ?>
                       <?php if($MySession->LoggedIn()): ?>
                           <ul class="wrapp_access">
                               <li>
                                   <a class="_access _logout" href="/logout.php"><?php echo _("Cerrar sesión"); ?></a>
                               </li>
                           </ul>
                       <?php endif; ?>
                   </div>
                        <div class="_panel_content">
                            <?php
                                $centro = $MyFrankyMonster->MyPHPFile();
                                $render_phtml = render(str_replace(".php",".phtml",$centro));
                                echo stripJS($render_phtml);
                            ?>
                        </div>

                </div>
        	</div>
        </main>
        <?php echo render("widget_link_up.phtml"); ?>
        <?php echo render("debug.phtml",$MyDebug->Dump()) ?>
        <?php echo render("admin/layout/css.async.phtml"); ?>
        <?php echo render("js.phtml",['render_phtml' => $render_phtml,'MyFrankyMonster' => $MyFrankyMonster,'MyConfigure' => $MyConfigure,'Mobile_detect' => $Mobile_detect,'MyMetatag' => $MyMetatag,'lang_root' => $lang_root,"MyRequest" => $MyRequest]); ?>
        <?php echo render("msg.request.phtml"); ?>
    </div>
</body>
</html>
