<div class="content">
    <div class="w-xxxx-12"><?php echo breadcrumbs(); ?></div>
    <h1 class="titulo_seccion_admin">Configuracion de sistema</h1>
    <?php echo $Form->openTag(); ?>
  
    <div class="w-xxxx-12">
    <?php
    if(!empty($core_config)):
      foreach($core_config as $key_config => $val_config):
        
            if(empty($seccion)){
                $seccion = $key_config;
            }
           
      
         
        
          ?>
          <div id="<?=$key_config?>" class="title_menu"><h3><a href="<?=$MyRequest->url(ADMIN_CORE_CONFIG_SECCION,['seccion' => $key_config])?>"><?=$val_config['menu']?></a></h3></div>
            
          <?php if($seccion == $key_config): ?>
          <div class="content_menu" >
          <?php
          foreach($val_config['config'] as $key =>$config):

              if(in_array($config['type'],['file','text','password'])):

                        if($config['type'] == 'file' && isset($core_config_db[$config['path']]) && !empty($core_config_db[$config['path']]))
                        {
                           $config['validation']['required'] =false;
                        }
                          $input = array(
                                'name' => str_replace("/","_",$config['path']),
                                'label' => _($config['label']),
                                'type'  => $config['type'],
                                'required' => ($config['validation']['required'] ? true : false),
                                'atributos' => array(
                                    'class' => (isset($config['validation']['image']) ? 'image ' : '').
                                                (isset($config['validation']['required']) && $config['validation']['required'] == true ? ' required ' : ''),
                                    'value' => (!isset($core_config_db[$config['path']]) ? '' : $core_config_db[$config['path']])
                                 )
                            );
                            if(isset($config['validation']['maxlength']))
                            {
                              $input['atributos']['maxlength'] = $config['validation']['maxlength'];
                            }
                            $Form->add($input);

              elseif(in_array($config['type'],['select'])):

                      $input = array(
                        'name' => str_replace("/","_",$config['path']),
                        'label' => _($config['label']),
                        'type'  => $config['type'],
                        'required' => ($config['validation']['required'] ? true : false),
                        'atributos' => array(
                            'class' => (isset($config['validation']['required']) && $config['validation']['required'] == true ? ' required ' : ''),
                            'value' => (!isset($core_config_db[$config['path']]) ? '' : $core_config_db[$config['path']])
                         ),
                         'options' => $config['data'],
                         'empty_option' => 'Elije...',
                    );
                if(isset($config['multiple']) && $config['multiple'] == true)
                {
                  $input['name'] = $input['name'].'[]';
                  $input['atributos']['multiple'] = 'multiple';
                  $input['atributos']['value'] = (!isset($core_config_db[$config['path']]) ? [] : json_decode($core_config_db[$config['path']],true));
                  unset($input['empty_option']);
                }
                $Form->add($input);

              endif;
              echo $Form->getRow($input['name']);
              if($config['type'] == 'file' && $config['validation']['image']): ?>
                  <div class="preview_<?=$input['name']?>">
                  <?php if(!empty($core_config_db[$config['path']])): ?>
                      <?php echo makeHTMLImg($core_config_db[$config['path']],"","","",'style="max-width: 100px;"'); ?>
                  <?php endif; ?>
                </div>
              <?php endif; 
               if(isset($config['html'])): ?>  
               <?=$config['html']?>
              <?php endif;


          endforeach; ?>
                <div class="w-xxxx-12">
            <?php echo $Form->getRow('guardar'); ?>

           </div>
        </div>
          <?php
          endif;
      endforeach;
         $Form->add(array(
               'name' => 'path', 'type'  =>'hidden',
               'atributos' => array(
                   'value' => $seccion
            ))); 
            echo $Form->getRow('path');
    endif;
    ?>
    </div>
  
    <?php echo $Form->endTag(); ?>
</div>

<script>
$(document).ready(function(){

        $("#frmConfig").validate();

        $(".image").change(function() {

                var self = $(this);
                if (this.files && this.files[0])
          			{
          					var reader = new FileReader();
          					reader.onload = function (e)
          					{

          							$('.preview_'+self.attr('name')).empty().html('<img style="max-width: 100px;" src="'+e.target.result+'" />');
          					}
          					reader.readAsDataURL(this.files[0]);
          			}

         });
        
});
$(window).load(function(){ 
    setTimeout(function(){
        $('html, body').animate({
            scrollTop: $("#<?=$seccion?>").offset().top
        }, 500,
    'linear')},1000);
});
</script>
