<div class="w_100 cont_admin_redes">

  <h2>Ligar mis cuentas:</h2>

  <div  class="check-fb-connect-confirmacion form-group form-inline">
	  <input type="checkbox" id="facebook_rel" name="facebook_rel"  <?php echo ($MyUserSocial->findSocial("", "facebook", $MySession->GetVar('id')) == REGISTRO_SUCCESS ? "checked='checked'" : ""); ?> />
	  <a class="btn btn-default" href="javascript:void(0)" title="facebook-connect" onclick="$('#facebook_rel').click().change()" >Facebook</a>

	  <input type="checkbox" id="twitter_rel"  name="twitter_rel" <?php echo ($MyUserSocial->findSocial("", "twitter", $MySession->GetVar('id')) == REGISTRO_SUCCESS ? "checked='checked'" : ""); ?> />
	  <a class="btn btn-default" href="javascript:void(0)" titel="twitter-connect" onclick="$('#twitter_rel').click().change()" >twitter</a>

	  <input type="checkbox" id="google_rel"  name="google_rel" <?php echo ($MyUserSocial->findSocial("", "google", $MySession->GetVar('id')) == REGISTRO_SUCCESS ? "checked='checked'" : ""); ?> />
	  <a class="btn btn-default" href="javascript:void(0)" titel="google-connect" onclick="$('#google_rel').click().change()" >Google +</a>
  </div>


</div>
