<div class="cont_nav_movil">
  <ul class="hamburguer">
      <li class="_one"></li>
      <li class="_two"></li>
      <li class="_three"></li>
  </ul>
</div>
<div class="_brand"><a class="a_logo" href="/"><?php echo makeHTMLImg(getImg("logo.png"),"","","","class=''"); ?></a></div>
<nav class="menu_web">
    <ul>
      <li class="_menu">
          <ul>
              <?php echo $MyMenuFront->getItemMenu("<li class=\"btn_nav \"><a href=\"%s\">%s</a></li>"); ?>
              <li><a href="<?=$MyRequest->url(CONTACTANOS)?>">CONTACTO</a></li>
          </ul>
      </li>
      <li class="_share">
          <ul class="_ul_redes">
              <li><a class="_li_share _face" target="_blank" href="https://www.facebook.com//"></a></li>
              <li><a class="_li_share _instagram" target="_blank"  href="https://www.instagram.com//"></a></li>
              <li><a class="_li_share _twitter" target="_blank"  href="https://twitter.com/"></a></li>
          </ul>
      </li>
      <li class="_login">
          <ul>
              <?php echo render( "widget_login.phtml"); ?>
          </ul>
      </li>
      <li class="_languaje">
          <ul>
              <?php if($_SESSION["lang"] == "es_MX"): ?><li class="first"><a href="/lang.php?lang=en_US&amp;callback=<?php echo $callbacks_idioma["en_US"]; ?>">EN</a></li><?php endif; ?>
              <?php if($_SESSION["lang"] == "en_US"): ?><li class="first"><a href="/lang.php?lang=es_MX&amp;callback=<?php echo $callbacks_idioma["es_MX"]; ?>">ES</a></li><?php endif; ?>
          </ul>
      </li>
    </ul>
</nav>
