<div class="w-xxxx-12">

		<div class="w-xxxx-12 footer_1">
			<div class="content">
				<div class="w-xxxx-7">
					<div class="w-xxxx-4">
						<h3>XXXXX</h3>
						<ul>
							<li><a href="#">XXXXXXXXXXX</a></li>
							<li><a href="#">XXXXXXXXXXX</a></li>
							<li><a href="#">XXXXXXXXXXX</a></li>
						</ul>
					</div>
					<div class="w-xxxx-4">
						<h3>XXXXXXXXXXX</h3>
						<ul>
							<li><a href="#">XXXXXXXXXXX</a></li>
							<li><a href="#">XXXXXXXXXXX</a></li>
							<li><a href="#">XXXXXXXXXXX</a></li>
						</ul>
					</div>
					<div class="w-xxxx-4">
						<h3>XXXXXXXXXXX</h3>
						<ul>
							<li><a href="#">XXXXXXXXXXX</a></li>
							<li><a href="#">XXXXXXXXXXX</a></li>
							<li><a href="#">XXXXXXXXXXX</a></li>
							<li><a href="#">XXXXXXXXXXX</a></li>
							<li><a href="#">XXXXXXXXXXX</a></li>
						</ul>
					</div>
				</div>
				<div class="w-xxxx-5">
					<div class="w-xxxx-7">
						<h3>Medios de contacto</h3>
						<ul class="no_bullet">
							<li><p><strong>Ciudad de México:</strong>
								<a href="#" class='tel1'>Tel. +52 (55) 00-00-00-0</a></p></li>
							<li><p>XXXXXXXX #XXX <br/>Col. XXXXXX, c.p. XXXXXX<br/>XXXXXX, XXXXX</p></li>
							<li><p><a href="mailto:contacto@cloudstudio.mx">contacto@cloudstudio.mx</a></p></li>
						</ul>
					</div>
					<div class="w-xxxx-5">
						<h3>Síguenos</h3>
						<ul class="no_bullet">
							<li><a href="#"><i class="icon icon-facebook"></i>  Facebook</a></li>
							<li><a href="#"><i class="icon icon-twitter"></i>  Twitter</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<div class="w-xxxx-12 footer_2">
			<div class="content">
				<div class="w-xxxx-12 align_right cont_legales">
					<a href="/">Condiciones de uso</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="/">Aviso de privacidad</a>
					<a class="logo_cloud" target="_blank" href="http://www.cloudstudio.mx">
		                <span>
		                    <object data="/public/skin/default/images/logo_cloud.svg" type="image/svg+xml" style="#">
		                        <!-- Implement fallback code here, or display a message: -->
		                        <img class="image_100" src="/public/skin/default/images/logo_cloud.png" alt="logo" />
		                   </object>
		                </span>
		            </a>
				</div>
			</div>
		</div>

</div>
