<div class="w-xxxx-12">
    <div class="content">
        <div class="w-xxxx-4 m-l-xxxx-4 wrapper_form">
            <h1 class="align_center">Recordar contraseña</h1>
            <div class="w-xxxx-12">
                <?php echo $forgotForm->openTag(); ?>
                <?php echo $forgotForm->getAllRow(); ?>
                <?php echo $forgotForm->endTag(); ?>
            	<a class="btn btn-text" href="<?php echo $MyRequest->url(LOGIN); ?>">Iniciar sesi&oacute;n</a>
            </div>
        </div>
    </div>
</div>
