<div class="w-xxxx-12">
    <div class="content">
        <?php echo render( "banners_home.phtml"); ?>
    </div>
</div>
<div class="w-xxxx-12">

    <div class="content">
        <div class="w-xxxx-12">
            <p>W12</p>
         </div>
         <div class="w-xxxx-12 w-x-6">
             <div class="w-xxxx-1 w-x-4"><p>W1</p></div>
             <div class="w-xxxx-11 w-x-8"><p>W11</p></div>
         </div>
         <div class="w-xxxx-12 w-x-6">
             <div class="w-xxxx-2 w-x-7"><p>W2</p></div>
             <div class="w-xxxx-10 w-x-5"><p>W10</p></div>
         </div>
         <div class="w-xxxx-12 w-x-6">
             <div class="w-xxxx-3"><p>W3</p></div>
             <div class="w-xxxx-9"><p>W9</p></div>
         </div>
         <div class="w-xxxx-12">
             <div class="w-xxxx-4"><p>W4</p></div>
             <div class="w-xxxx-8"><p>W8</p></div>
         </div>
         <div class="w-xxxx-12 w-xxx-6">
             <div class="w-xxxx-5"><p>W5</p></div>
             <div class="w-xxxx-7"><p>W7</p></div>
         </div>
         <div class="w-xxxx-12 w-xxx-6">
             <div class="w-xxxx-6"><p>W6</p></div>
             <div class="w-xxxx-6"><p>W6</p></div>
         </div>
         <div class="w-xxxx-12">
             <div class="w-xxxx-7 w-xxx-2 w-xx-11"><p>W7</p></div>
             <div class="w-xxxx-5 w-xxx-10 w-xx-1"><p>W5</p></div>
         </div>
         <div class="w-xxxx-12">
             <div class="w-xxxx-8"><p>W8</p></div>
             <div class="w-xxxx-4"><p>W4</p></div>
         </div>
         <div class="w-xxxx-12">
             <div class="w-xxxx-9"><p>W9</p></div>
             <div class="w-xxxx-3"><p>W3</p></div>
         </div>
         <div class="w-xxxx-12">
             <div class="w-xxxx-10"><p>W10</p></div>
             <div class="w-xxxx-2"><p>W2</p></div>
         </div>
         <div class="w-xxxx-12">
             <div class="w-xxxx-11"><p>W11</p></div>
             <div class="w-xxxx-1"><p>W1</p></div>
         </div>
    </div>
</div>
