<!DOCTYPE html>
<html lang="<?php echo $lang_root; ?>">
<head>
    <?php if($MyRequest->getPROTOCOLO() == "https://" && $Mobile_detect->isMobile()): ?>
        <link rel="manifest" href="/manifest.json">
        <meta name="theme-color" content="<?=getCoreConfig('base/pwa/theme-color')?>">
        <?php if(getCoreConfig('base/pwa/iconios') != ""): ?>
            <meta name="apple-mobile-web-app-capable" content="yes">
            <meta name="apple-mobile-web-app-status-bar-style" content="black">
            <meta name="apple-mobile-web-app-title" content="<?=getCoreConfig('base/pwa/name')?>">
            <link rel="apple-touch-icon" href="<?=imageResize(getCoreConfig('base/pwa/iconios') ,192,192,true)?>">
            <link rel="apple-touch-icon" sizes="76x76" href="<?=imageResize(getCoreConfig('base/pwa/iconios') ,76,76,true)?>">
            <link rel="apple-touch-icon" sizes="120x120" href="<?=imageResize(getCoreConfig('base/pwa/iconios') ,120,120,true)?>">
            <link rel="apple-touch-icon" sizes="152x152" href="<?=imageResize(getCoreConfig('base/pwa/iconios') ,152,152,true)?>">
        <?php endif; ?>
    <?php endif; ?>
   <?php  include(getVista("widget.headers.phtml")); ?>
</head>
<body class="<?php echo $MyRequest->getClassBody($lang_root); ?>" <?php echo (!$MyRequest->isAjax() ? 'style="overflow: hidden;"' : ''); ?>>

<?php echo render("principal_schema.phtml"); ?>
<?php if(!$MyRequest->isAjax()): ?>
    <div id="preloaderfullpage" style="position: fixed;top:0;left:0;right:0; bottom:0;background: #f7f7f7;z-index: 100;">
        <div id="loader" style="width: 100px;height: 100px;position: absolute;left:50%; top:50%;background: url('<?php echo getImg('SVG/loader.svg'); ?>') no-repeat center 0; margin:-50px 0 0 -50px;">&nbsp;</div>
    </div>
<?php endif; ?>
<header>
	<div class="w-xxxx-12 header_wrapper">
		<?php echo render("header.phtml"); ?>
	</div>
</header>
<main>
	<div class="w-xxxx-12 page_wrapper">
		<div class="one_column">
			<div class="wrapper _body">
        <?php
            $centro = $MyFrankyMonster->MyPHPFile();
            $render_phtml = render(str_replace(".php",".phtml",$centro));
            echo stripJS($render_phtml);
        ?>

			</div>
		</div>
	</div>
</main>
<footer>
    <div class="w-xxxx-12 footer_wrapper">
        <?php echo render("footer.phtml"); ?>
    </div>
</footer>
<?php echo render("widget_link_up.phtml"); ?>
<?php echo render("debug.phtml",$MyDebug->Dump()) ?>
<?php echo render("css.async.phtml"); ?>
<?php echo render("js.phtml",['render_phtml' => $render_phtml,'MyFrankyMonster' => $MyFrankyMonster,'MyConfigure' => $MyConfigure,'Mobile_detect' => $Mobile_detect,'MyMetatag' => $MyMetatag,'lang_root' => $lang_root, 'MyRequest' => $MyRequest]); ?>
<?php echo render("msg.request.phtml"); ?>
</body>
</html>
